### ISSUE TITLE
Client-side instead of server-side redirect

### ISSUE THREAD

**Issue by sedubois** [angeloocana/ptz-i18n#2]
Hi and thanks for sharing this as part of gatsby-plugin-i18n 🙂 

I've been integrating your gatsby-started-default-i18n example, which works well now, but one thing I noticed is that it uses `redirectToHome` from this lib which does a `window.location.replace`, leading to a flash of content while the whole page reloads. 

Wouldn't it be better to do a client-side redirect (with gatsby-link I guess)? This way, even if the `/` route is only visible for a split second, it would be possible to render styles in there while transitioning smoothly to the proper lang route (`/en/`, etc).

**Comment by angeloocana** [comment]
Awesome!!!!!!!!!!!!!!!!!!!!!!!

Thank you!
